apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keyip.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "keyip.labels" . | nindent 4 }}
    {{- include "keyip.partOf" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.config | indent 4 }}
