// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a stub file for compilation compatibility.
// For production, generate from molecule.proto using protoc.

package moleculev1

// Molecule represents a molecule message.
type Molecule struct {
	MoleculeId   string            `json:"molecule_id,omitempty"`
	Smiles       string            `json:"smiles,omitempty"`
	Inchi        string            `json:"inchi,omitempty"`
	Name         string            `json:"name,omitempty"`
	MoleculeType string            `json:"molecule_type,omitempty"`
	OledLayer    string            `json:"oled_layer,omitempty"`
	Properties   map[string]string `json:"properties,omitempty"`
	Metadata     map[string]string `json:"metadata,omitempty"`
	CreatedAt    int64             `json:"created_at,omitempty"`
	UpdatedAt    int64             `json:"updated_at,omitempty"`
}

// GetMoleculeRequest is the request for GetMolecule.
type GetMoleculeRequest struct {
	MoleculeId string `json:"molecule_id,omitempty"`
}

// GetMoleculeResponse is the response for GetMolecule.
type GetMoleculeResponse struct {
	Molecule *Molecule `json:"molecule,omitempty"`
}

// CreateMoleculeRequest is the request for CreateMolecule.
type CreateMoleculeRequest struct {
	Smiles       string            `json:"smiles,omitempty"`
	Inchi        string            `json:"inchi,omitempty"`
	Name         string            `json:"name,omitempty"`
	MoleculeType string            `json:"molecule_type,omitempty"`
	OledLayer    string            `json:"oled_layer,omitempty"`
	Properties   map[string]string `json:"properties,omitempty"`
	Metadata     map[string]string `json:"metadata,omitempty"`
}

// CreateMoleculeResponse is the response for CreateMolecule.
type CreateMoleculeResponse struct {
	Molecule *Molecule `json:"molecule,omitempty"`
}

// UpdateMoleculeRequest is the request for UpdateMolecule.
type UpdateMoleculeRequest struct {
	MoleculeId string            `json:"molecule_id,omitempty"`
	Name       string            `json:"name,omitempty"`
	Properties map[string]string `json:"properties,omitempty"`
	Metadata   map[string]string `json:"metadata,omitempty"`
}

// UpdateMoleculeResponse is the response for UpdateMolecule.
type UpdateMoleculeResponse struct {
	Molecule *Molecule `json:"molecule,omitempty"`
}

// DeleteMoleculeRequest is the request for DeleteMolecule.
type DeleteMoleculeRequest struct {
	MoleculeId string `json:"molecule_id,omitempty"`
}

// DeleteMoleculeResponse is the response for DeleteMolecule.
type DeleteMoleculeResponse struct {
	Success bool `json:"success,omitempty"`
}

// ListMoleculesRequest is the request for ListMolecules.
type ListMoleculesRequest struct {
	PageSize     int32  `json:"page_size,omitempty"`
	PageToken    string `json:"page_token,omitempty"`
	MoleculeType string `json:"molecule_type,omitempty"`
	OledLayer    string `json:"oled_layer,omitempty"`
	SortBy       string `json:"sort_by,omitempty"`
}

// ListMoleculesResponse is the response for ListMolecules.
type ListMoleculesResponse struct {
	Molecules     []*Molecule `json:"molecules,omitempty"`
	NextPageToken string      `json:"next_page_token,omitempty"`
	TotalCount    int64       `json:"total_count,omitempty"`
}

// SearchSimilarRequest is the request for SearchSimilar.
type SearchSimilarRequest struct {
	Smiles          string  `json:"smiles,omitempty"`
	Inchi           string  `json:"inchi,omitempty"`
	Threshold       float64 `json:"threshold,omitempty"`
	FingerprintType string  `json:"fingerprint_type,omitempty"`
	MaxResults      int32   `json:"max_results,omitempty"`
}

// SimilarMolecule represents a similar molecule with score.
type SimilarMolecule struct {
	Molecule   *Molecule `json:"molecule,omitempty"`
	Similarity float64   `json:"similarity,omitempty"`
	Method     string    `json:"method,omitempty"`
}

// SearchSimilarResponse is the response for SearchSimilar.
type SearchSimilarResponse struct {
	SimilarMolecules []*SimilarMolecule `json:"similar_molecules,omitempty"`
}

// PredictPropertiesRequest is the request for PredictProperties.
type PredictPropertiesRequest struct {
	Smiles string `json:"smiles,omitempty"`
}

// PredictPropertiesResponse is the response for PredictProperties.
type PredictPropertiesResponse struct {
	Homo               float32 `json:"homo,omitempty"`
	Lumo               float32 `json:"lumo,omitempty"`
	BandGap            float32 `json:"band_gap,omitempty"`
	EmissionWavelength float32 `json:"emission_wavelength,omitempty"`
	QuantumYield       float32 `json:"quantum_yield,omitempty"`
	Stability          float32 `json:"stability,omitempty"`
	Confidence         float32 `json:"confidence,omitempty"`
}

//Personal.AI order the ending
