// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// This is a stub file for compilation compatibility.
// For production, generate from molecule.proto using protoc.

package moleculev1

import (
	"context"

	"google.golang.org/grpc"
)

// MoleculeServiceClient is the client API for MoleculeService service.
type MoleculeServiceClient interface {
	GetMolecule(ctx context.Context, in *GetMoleculeRequest, opts ...grpc.CallOption) (*GetMoleculeResponse, error)
	CreateMolecule(ctx context.Context, in *CreateMoleculeRequest, opts ...grpc.CallOption) (*CreateMoleculeResponse, error)
	UpdateMolecule(ctx context.Context, in *UpdateMoleculeRequest, opts ...grpc.CallOption) (*UpdateMoleculeResponse, error)
	DeleteMolecule(ctx context.Context, in *DeleteMoleculeRequest, opts ...grpc.CallOption) (*DeleteMoleculeResponse, error)
	ListMolecules(ctx context.Context, in *ListMoleculesRequest, opts ...grpc.CallOption) (*ListMoleculesResponse, error)
	SearchSimilar(ctx context.Context, in *SearchSimilarRequest, opts ...grpc.CallOption) (*SearchSimilarResponse, error)
	PredictProperties(ctx context.Context, in *PredictPropertiesRequest, opts ...grpc.CallOption) (*PredictPropertiesResponse, error)
}

type moleculeServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewMoleculeServiceClient creates a new MoleculeServiceClient.
func NewMoleculeServiceClient(cc grpc.ClientConnInterface) MoleculeServiceClient {
	return &moleculeServiceClient{cc}
}

func (c *moleculeServiceClient) GetMolecule(ctx context.Context, in *GetMoleculeRequest, opts ...grpc.CallOption) (*GetMoleculeResponse, error) {
	out := new(GetMoleculeResponse)
	err := c.cc.Invoke(ctx, "/molecule.v1.MoleculeService/GetMolecule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moleculeServiceClient) CreateMolecule(ctx context.Context, in *CreateMoleculeRequest, opts ...grpc.CallOption) (*CreateMoleculeResponse, error) {
	out := new(CreateMoleculeResponse)
	err := c.cc.Invoke(ctx, "/molecule.v1.MoleculeService/CreateMolecule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moleculeServiceClient) UpdateMolecule(ctx context.Context, in *UpdateMoleculeRequest, opts ...grpc.CallOption) (*UpdateMoleculeResponse, error) {
	out := new(UpdateMoleculeResponse)
	err := c.cc.Invoke(ctx, "/molecule.v1.MoleculeService/UpdateMolecule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moleculeServiceClient) DeleteMolecule(ctx context.Context, in *DeleteMoleculeRequest, opts ...grpc.CallOption) (*DeleteMoleculeResponse, error) {
	out := new(DeleteMoleculeResponse)
	err := c.cc.Invoke(ctx, "/molecule.v1.MoleculeService/DeleteMolecule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moleculeServiceClient) ListMolecules(ctx context.Context, in *ListMoleculesRequest, opts ...grpc.CallOption) (*ListMoleculesResponse, error) {
	out := new(ListMoleculesResponse)
	err := c.cc.Invoke(ctx, "/molecule.v1.MoleculeService/ListMolecules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moleculeServiceClient) SearchSimilar(ctx context.Context, in *SearchSimilarRequest, opts ...grpc.CallOption) (*SearchSimilarResponse, error) {
	out := new(SearchSimilarResponse)
	err := c.cc.Invoke(ctx, "/molecule.v1.MoleculeService/SearchSimilar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moleculeServiceClient) PredictProperties(ctx context.Context, in *PredictPropertiesRequest, opts ...grpc.CallOption) (*PredictPropertiesResponse, error) {
	out := new(PredictPropertiesResponse)
	err := c.cc.Invoke(ctx, "/molecule.v1.MoleculeService/PredictProperties", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoleculeServiceServer is the server API for MoleculeService service.
type MoleculeServiceServer interface {
	GetMolecule(context.Context, *GetMoleculeRequest) (*GetMoleculeResponse, error)
	CreateMolecule(context.Context, *CreateMoleculeRequest) (*CreateMoleculeResponse, error)
	UpdateMolecule(context.Context, *UpdateMoleculeRequest) (*UpdateMoleculeResponse, error)
	DeleteMolecule(context.Context, *DeleteMoleculeRequest) (*DeleteMoleculeResponse, error)
	ListMolecules(context.Context, *ListMoleculesRequest) (*ListMoleculesResponse, error)
	SearchSimilar(context.Context, *SearchSimilarRequest) (*SearchSimilarResponse, error)
	PredictProperties(context.Context, *PredictPropertiesRequest) (*PredictPropertiesResponse, error)
	mustEmbedUnimplementedMoleculeServiceServer()
}

// UnimplementedMoleculeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMoleculeServiceServer struct{}

func (UnimplementedMoleculeServiceServer) GetMolecule(context.Context, *GetMoleculeRequest) (*GetMoleculeResponse, error) {
	return nil, nil
}
func (UnimplementedMoleculeServiceServer) CreateMolecule(context.Context, *CreateMoleculeRequest) (*CreateMoleculeResponse, error) {
	return nil, nil
}
func (UnimplementedMoleculeServiceServer) UpdateMolecule(context.Context, *UpdateMoleculeRequest) (*UpdateMoleculeResponse, error) {
	return nil, nil
}
func (UnimplementedMoleculeServiceServer) DeleteMolecule(context.Context, *DeleteMoleculeRequest) (*DeleteMoleculeResponse, error) {
	return nil, nil
}
func (UnimplementedMoleculeServiceServer) ListMolecules(context.Context, *ListMoleculesRequest) (*ListMoleculesResponse, error) {
	return nil, nil
}
func (UnimplementedMoleculeServiceServer) SearchSimilar(context.Context, *SearchSimilarRequest) (*SearchSimilarResponse, error) {
	return nil, nil
}
func (UnimplementedMoleculeServiceServer) PredictProperties(context.Context, *PredictPropertiesRequest) (*PredictPropertiesResponse, error) {
	return nil, nil
}
func (UnimplementedMoleculeServiceServer) mustEmbedUnimplementedMoleculeServiceServer() {}

// UnsafeMoleculeServiceServer may be embedded to opt out of forward compatibility.
type UnsafeMoleculeServiceServer interface {
	mustEmbedUnimplementedMoleculeServiceServer()
}

// RegisterMoleculeServiceServer registers the MoleculeServiceServer with the grpc.Server.
func RegisterMoleculeServiceServer(s grpc.ServiceRegistrar, srv MoleculeServiceServer) {
	s.RegisterService(&MoleculeService_ServiceDesc, srv)
}

// MoleculeService_ServiceDesc is the grpc.ServiceDesc for MoleculeService service.
var MoleculeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "molecule.v1.MoleculeService",
	HandlerType: (*MoleculeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "GetMolecule", Handler: nil},
		{MethodName: "CreateMolecule", Handler: nil},
		{MethodName: "UpdateMolecule", Handler: nil},
		{MethodName: "DeleteMolecule", Handler: nil},
		{MethodName: "ListMolecules", Handler: nil},
		{MethodName: "SearchSimilar", Handler: nil},
		{MethodName: "PredictProperties", Handler: nil},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "molecule/v1/molecule.proto",
}

//Personal.AI order the ending
