// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// This is a stub file for compilation compatibility.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MoleculeServiceClient is the client API for MoleculeService service.
type MoleculeServiceClient interface {
	GetMolecule(ctx context.Context, in *GetMoleculeRequest, opts ...grpc.CallOption) (*GetMoleculeResponse, error)
	ListMolecules(ctx context.Context, in *ListMoleculesRequest, opts ...grpc.CallOption) (*ListMoleculesResponse, error)
	CreateMolecule(ctx context.Context, in *CreateMoleculeRequest, opts ...grpc.CallOption) (*CreateMoleculeResponse, error)
	DeleteMolecule(ctx context.Context, in *DeleteMoleculeRequest, opts ...grpc.CallOption) (*DeleteMoleculeResponse, error)
	// SimilaritySearch searches the patent corpus for molecules structurally
	// similar to the query molecule and returns ranked results with optional
	// infringement risk scores.
	SimilaritySearch(ctx context.Context, in *SimilaritySearchRequest, opts ...grpc.CallOption) (*SimilaritySearchResponse, error)
	// BatchSimilaritySearch performs SimilaritySearch for multiple molecules
	// concurrently and streams results as they complete. Partial failures (one
	// molecule's search fails) are reported per-item; the stream is not aborted.
	BatchSimilaritySearch(ctx context.Context, in *BatchSimilaritySearchRequest, opts ...grpc.CallOption) (MoleculeService_BatchSimilaritySearchClient, error)
	// AssessPatentability evaluates novelty, inventive step, and utility for a
	// registered molecule against the patent prior-art corpus.
	AssessPatentability(ctx context.Context, in *AssessPatentabilityRequest, opts ...grpc.CallOption) (*AssessPatentabilityResponse, error)

	// Legacy methods
	UpdateMolecule(ctx context.Context, in *UpdateMoleculeRequest, opts ...grpc.CallOption) (*UpdateMoleculeResponse, error)
	SearchSimilar(ctx context.Context, in *SearchSimilarRequest, opts ...grpc.CallOption) (*SearchSimilarResponse, error)
	PredictProperties(ctx context.Context, in *PredictPropertiesRequest, opts ...grpc.CallOption) (*PredictPropertiesResponse, error)
}

type moleculeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMoleculeServiceClient(cc grpc.ClientConnInterface) MoleculeServiceClient {
	return &moleculeServiceClient{cc}
}

func (c *moleculeServiceClient) GetMolecule(ctx context.Context, in *GetMoleculeRequest, opts ...grpc.CallOption) (*GetMoleculeResponse, error) {
	out := new(GetMoleculeResponse)
	err := c.cc.Invoke(ctx, "/keyip.v1.MoleculeService/GetMolecule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moleculeServiceClient) ListMolecules(ctx context.Context, in *ListMoleculesRequest, opts ...grpc.CallOption) (*ListMoleculesResponse, error) {
	out := new(ListMoleculesResponse)
	err := c.cc.Invoke(ctx, "/keyip.v1.MoleculeService/ListMolecules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moleculeServiceClient) CreateMolecule(ctx context.Context, in *CreateMoleculeRequest, opts ...grpc.CallOption) (*CreateMoleculeResponse, error) {
	out := new(CreateMoleculeResponse)
	err := c.cc.Invoke(ctx, "/keyip.v1.MoleculeService/CreateMolecule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moleculeServiceClient) DeleteMolecule(ctx context.Context, in *DeleteMoleculeRequest, opts ...grpc.CallOption) (*DeleteMoleculeResponse, error) {
	out := new(DeleteMoleculeResponse)
	err := c.cc.Invoke(ctx, "/keyip.v1.MoleculeService/DeleteMolecule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moleculeServiceClient) SimilaritySearch(ctx context.Context, in *SimilaritySearchRequest, opts ...grpc.CallOption) (*SimilaritySearchResponse, error) {
	out := new(SimilaritySearchResponse)
	err := c.cc.Invoke(ctx, "/keyip.v1.MoleculeService/SimilaritySearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moleculeServiceClient) BatchSimilaritySearch(ctx context.Context, in *BatchSimilaritySearchRequest, opts ...grpc.CallOption) (MoleculeService_BatchSimilaritySearchClient, error) {
	stream, err := c.cc.NewStream(ctx, &MoleculeService_ServiceDesc.Streams[0], "/keyip.v1.MoleculeService/BatchSimilaritySearch", opts...)
	if err != nil {
		return nil, err
	}
	x := &moleculeServiceBatchSimilaritySearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MoleculeService_BatchSimilaritySearchClient interface {
	Recv() (*BatchSimilaritySearchItem, error)
	grpc.ClientStream
}

type moleculeServiceBatchSimilaritySearchClient struct {
	grpc.ClientStream
}

func (x *moleculeServiceBatchSimilaritySearchClient) Recv() (*BatchSimilaritySearchItem, error) {
	m := new(BatchSimilaritySearchItem)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *moleculeServiceClient) AssessPatentability(ctx context.Context, in *AssessPatentabilityRequest, opts ...grpc.CallOption) (*AssessPatentabilityResponse, error) {
	out := new(AssessPatentabilityResponse)
	err := c.cc.Invoke(ctx, "/keyip.v1.MoleculeService/AssessPatentability", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moleculeServiceClient) UpdateMolecule(ctx context.Context, in *UpdateMoleculeRequest, opts ...grpc.CallOption) (*UpdateMoleculeResponse, error) {
	out := new(UpdateMoleculeResponse)
	err := c.cc.Invoke(ctx, "/keyip.v1.MoleculeService/UpdateMolecule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moleculeServiceClient) SearchSimilar(ctx context.Context, in *SearchSimilarRequest, opts ...grpc.CallOption) (*SearchSimilarResponse, error) {
	out := new(SearchSimilarResponse)
	err := c.cc.Invoke(ctx, "/keyip.v1.MoleculeService/SearchSimilar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moleculeServiceClient) PredictProperties(ctx context.Context, in *PredictPropertiesRequest, opts ...grpc.CallOption) (*PredictPropertiesResponse, error) {
	out := new(PredictPropertiesResponse)
	err := c.cc.Invoke(ctx, "/keyip.v1.MoleculeService/PredictProperties", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoleculeServiceServer is the server API for MoleculeService service.
// All implementations must embed UnimplementedMoleculeServiceServer
// for forward compatibility
type MoleculeServiceServer interface {
	GetMolecule(context.Context, *GetMoleculeRequest) (*GetMoleculeResponse, error)
	ListMolecules(context.Context, *ListMoleculesRequest) (*ListMoleculesResponse, error)
	CreateMolecule(context.Context, *CreateMoleculeRequest) (*CreateMoleculeResponse, error)
	DeleteMolecule(context.Context, *DeleteMoleculeRequest) (*DeleteMoleculeResponse, error)
	// SimilaritySearch searches the patent corpus for molecules structurally
	// similar to the query molecule and returns ranked results with optional
	// infringement risk scores.
	SimilaritySearch(context.Context, *SimilaritySearchRequest) (*SimilaritySearchResponse, error)
	// BatchSimilaritySearch performs SimilaritySearch for multiple molecules
	// concurrently and streams results as they complete. Partial failures (one
	// molecule's search fails) are reported per-item; the stream is not aborted.
	BatchSimilaritySearch(*BatchSimilaritySearchRequest, MoleculeService_BatchSimilaritySearchServer) error
	// AssessPatentability evaluates novelty, inventive step, and utility for a
	// registered molecule against the patent prior-art corpus.
	AssessPatentability(context.Context, *AssessPatentabilityRequest) (*AssessPatentabilityResponse, error)

	// Legacy methods
	UpdateMolecule(context.Context, *UpdateMoleculeRequest) (*UpdateMoleculeResponse, error)
	SearchSimilar(context.Context, *SearchSimilarRequest) (*SearchSimilarResponse, error)
	PredictProperties(context.Context, *PredictPropertiesRequest) (*PredictPropertiesResponse, error)

	mustEmbedUnimplementedMoleculeServiceServer()
}

// UnimplementedMoleculeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMoleculeServiceServer struct {
}

func (UnimplementedMoleculeServiceServer) GetMolecule(context.Context, *GetMoleculeRequest) (*GetMoleculeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMolecule not implemented")
}
func (UnimplementedMoleculeServiceServer) ListMolecules(context.Context, *ListMoleculesRequest) (*ListMoleculesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMolecules not implemented")
}
func (UnimplementedMoleculeServiceServer) CreateMolecule(context.Context, *CreateMoleculeRequest) (*CreateMoleculeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMolecule not implemented")
}
func (UnimplementedMoleculeServiceServer) DeleteMolecule(context.Context, *DeleteMoleculeRequest) (*DeleteMoleculeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMolecule not implemented")
}
func (UnimplementedMoleculeServiceServer) SimilaritySearch(context.Context, *SimilaritySearchRequest) (*SimilaritySearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimilaritySearch not implemented")
}
func (UnimplementedMoleculeServiceServer) BatchSimilaritySearch(*BatchSimilaritySearchRequest, MoleculeService_BatchSimilaritySearchServer) error {
	return status.Errorf(codes.Unimplemented, "method BatchSimilaritySearch not implemented")
}
func (UnimplementedMoleculeServiceServer) AssessPatentability(context.Context, *AssessPatentabilityRequest) (*AssessPatentabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssessPatentability not implemented")
}
func (UnimplementedMoleculeServiceServer) UpdateMolecule(context.Context, *UpdateMoleculeRequest) (*UpdateMoleculeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMolecule not implemented")
}
func (UnimplementedMoleculeServiceServer) SearchSimilar(context.Context, *SearchSimilarRequest) (*SearchSimilarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchSimilar not implemented")
}
func (UnimplementedMoleculeServiceServer) PredictProperties(context.Context, *PredictPropertiesRequest) (*PredictPropertiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PredictProperties not implemented")
}
func (UnimplementedMoleculeServiceServer) mustEmbedUnimplementedMoleculeServiceServer() {}

// UnsafeMoleculeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MoleculeServiceServer will
// result in compilation errors.
type UnsafeMoleculeServiceServer interface {
	mustEmbedUnimplementedMoleculeServiceServer()
}

func RegisterMoleculeServiceServer(s grpc.ServiceRegistrar, srv MoleculeServiceServer) {
	s.RegisterService(&MoleculeService_ServiceDesc, srv)
}

func _MoleculeService_GetMolecule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMoleculeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoleculeServiceServer).GetMolecule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keyip.v1.MoleculeService/GetMolecule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoleculeServiceServer).GetMolecule(ctx, req.(*GetMoleculeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoleculeService_ListMolecules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMoleculesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoleculeServiceServer).ListMolecules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keyip.v1.MoleculeService/ListMolecules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoleculeServiceServer).ListMolecules(ctx, req.(*ListMoleculesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoleculeService_CreateMolecule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMoleculeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoleculeServiceServer).CreateMolecule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keyip.v1.MoleculeService/CreateMolecule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoleculeServiceServer).CreateMolecule(ctx, req.(*CreateMoleculeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoleculeService_DeleteMolecule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMoleculeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoleculeServiceServer).DeleteMolecule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keyip.v1.MoleculeService/DeleteMolecule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoleculeServiceServer).DeleteMolecule(ctx, req.(*DeleteMoleculeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoleculeService_SimilaritySearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimilaritySearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoleculeServiceServer).SimilaritySearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keyip.v1.MoleculeService/SimilaritySearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoleculeServiceServer).SimilaritySearch(ctx, req.(*SimilaritySearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoleculeService_BatchSimilaritySearch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BatchSimilaritySearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MoleculeServiceServer).BatchSimilaritySearch(m, &moleculeServiceBatchSimilaritySearchServer{stream})
}

type MoleculeService_BatchSimilaritySearchServer interface {
	Send(*BatchSimilaritySearchItem) error
	grpc.ServerStream
}

type moleculeServiceBatchSimilaritySearchServer struct {
	grpc.ServerStream
}

func (x *moleculeServiceBatchSimilaritySearchServer) Send(m *BatchSimilaritySearchItem) error {
	return x.ServerStream.SendMsg(m)
}

func _MoleculeService_AssessPatentability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssessPatentabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoleculeServiceServer).AssessPatentability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keyip.v1.MoleculeService/AssessPatentability",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoleculeServiceServer).AssessPatentability(ctx, req.(*AssessPatentabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoleculeService_UpdateMolecule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMoleculeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoleculeServiceServer).UpdateMolecule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keyip.v1.MoleculeService/UpdateMolecule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoleculeServiceServer).UpdateMolecule(ctx, req.(*UpdateMoleculeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoleculeService_SearchSimilar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSimilarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoleculeServiceServer).SearchSimilar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keyip.v1.MoleculeService/SearchSimilar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoleculeServiceServer).SearchSimilar(ctx, req.(*SearchSimilarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoleculeService_PredictProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictPropertiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoleculeServiceServer).PredictProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keyip.v1.MoleculeService/PredictProperties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoleculeServiceServer).PredictProperties(ctx, req.(*PredictPropertiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MoleculeService_ServiceDesc is the grpc.ServiceDesc for MoleculeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MoleculeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keyip.v1.MoleculeService",
	HandlerType: (*MoleculeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMolecule",
			Handler:    _MoleculeService_GetMolecule_Handler,
		},
		{
			MethodName: "ListMolecules",
			Handler:    _MoleculeService_ListMolecules_Handler,
		},
		{
			MethodName: "CreateMolecule",
			Handler:    _MoleculeService_CreateMolecule_Handler,
		},
		{
			MethodName: "DeleteMolecule",
			Handler:    _MoleculeService_DeleteMolecule_Handler,
		},
		{
			MethodName: "SimilaritySearch",
			Handler:    _MoleculeService_SimilaritySearch_Handler,
		},
		{
			MethodName: "AssessPatentability",
			Handler:    _MoleculeService_AssessPatentability_Handler,
		},
		{
			MethodName: "UpdateMolecule",
			Handler:    _MoleculeService_UpdateMolecule_Handler,
		},
		{
			MethodName: "SearchSimilar",
			Handler:    _MoleculeService_SearchSimilar_Handler,
		},
		{
			MethodName: "PredictProperties",
			Handler:    _MoleculeService_PredictProperties_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BatchSimilaritySearch",
			Handler:       _MoleculeService_BatchSimilaritySearch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "molecule.proto",
}
