// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// This is a stub file for compilation compatibility.
// For production, generate from patent.proto using protoc.

package v1

import (
	"context"

	"google.golang.org/grpc"
)

// PatentServiceClient is the client API for PatentService service.
type PatentServiceClient interface {
	GetPatent(ctx context.Context, in *GetPatentRequest, opts ...grpc.CallOption) (*GetPatentResponse, error)
	SearchPatents(ctx context.Context, in *SearchPatentsRequest, opts ...grpc.CallOption) (*SearchPatentsResponse, error)
	AnalyzeClaims(ctx context.Context, in *AnalyzeClaimsRequest, opts ...grpc.CallOption) (*AnalyzeClaimsResponse, error)
	CheckFTO(ctx context.Context, in *CheckFTORequest, opts ...grpc.CallOption) (*CheckFTOResponse, error)
	GetPatentFamily(ctx context.Context, in *GetPatentFamilyRequest, opts ...grpc.CallOption) (*GetPatentFamilyResponse, error)
	GetCitationNetwork(ctx context.Context, in *GetCitationNetworkRequest, opts ...grpc.CallOption) (*GetCitationNetworkResponse, error)
}

type patentServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewPatentServiceClient creates a new PatentServiceClient.
func NewPatentServiceClient(cc grpc.ClientConnInterface) PatentServiceClient {
	return &patentServiceClient{cc}
}

func (c *patentServiceClient) GetPatent(ctx context.Context, in *GetPatentRequest, opts ...grpc.CallOption) (*GetPatentResponse, error) {
	out := new(GetPatentResponse)
	err := c.cc.Invoke(ctx, "/patent.v1.PatentService/GetPatent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patentServiceClient) SearchPatents(ctx context.Context, in *SearchPatentsRequest, opts ...grpc.CallOption) (*SearchPatentsResponse, error) {
	out := new(SearchPatentsResponse)
	err := c.cc.Invoke(ctx, "/patent.v1.PatentService/SearchPatents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patentServiceClient) AnalyzeClaims(ctx context.Context, in *AnalyzeClaimsRequest, opts ...grpc.CallOption) (*AnalyzeClaimsResponse, error) {
	out := new(AnalyzeClaimsResponse)
	err := c.cc.Invoke(ctx, "/patent.v1.PatentService/AnalyzeClaims", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patentServiceClient) CheckFTO(ctx context.Context, in *CheckFTORequest, opts ...grpc.CallOption) (*CheckFTOResponse, error) {
	out := new(CheckFTOResponse)
	err := c.cc.Invoke(ctx, "/patent.v1.PatentService/CheckFTO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patentServiceClient) GetPatentFamily(ctx context.Context, in *GetPatentFamilyRequest, opts ...grpc.CallOption) (*GetPatentFamilyResponse, error) {
	out := new(GetPatentFamilyResponse)
	err := c.cc.Invoke(ctx, "/patent.v1.PatentService/GetPatentFamily", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patentServiceClient) GetCitationNetwork(ctx context.Context, in *GetCitationNetworkRequest, opts ...grpc.CallOption) (*GetCitationNetworkResponse, error) {
	out := new(GetCitationNetworkResponse)
	err := c.cc.Invoke(ctx, "/patent.v1.PatentService/GetCitationNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PatentServiceServer is the server API for PatentService service.
type PatentServiceServer interface {
	GetPatent(context.Context, *GetPatentRequest) (*GetPatentResponse, error)
	SearchPatents(context.Context, *SearchPatentsRequest) (*SearchPatentsResponse, error)
	AnalyzeClaims(context.Context, *AnalyzeClaimsRequest) (*AnalyzeClaimsResponse, error)
	CheckFTO(context.Context, *CheckFTORequest) (*CheckFTOResponse, error)
	GetPatentFamily(context.Context, *GetPatentFamilyRequest) (*GetPatentFamilyResponse, error)
	GetCitationNetwork(context.Context, *GetCitationNetworkRequest) (*GetCitationNetworkResponse, error)
	mustEmbedUnimplementedPatentServiceServer()
}

// UnimplementedPatentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPatentServiceServer struct{}

func (UnimplementedPatentServiceServer) GetPatent(context.Context, *GetPatentRequest) (*GetPatentResponse, error) {
	return nil, nil
}
func (UnimplementedPatentServiceServer) SearchPatents(context.Context, *SearchPatentsRequest) (*SearchPatentsResponse, error) {
	return nil, nil
}
func (UnimplementedPatentServiceServer) AnalyzeClaims(context.Context, *AnalyzeClaimsRequest) (*AnalyzeClaimsResponse, error) {
	return nil, nil
}
func (UnimplementedPatentServiceServer) CheckFTO(context.Context, *CheckFTORequest) (*CheckFTOResponse, error) {
	return nil, nil
}
func (UnimplementedPatentServiceServer) GetPatentFamily(context.Context, *GetPatentFamilyRequest) (*GetPatentFamilyResponse, error) {
	return nil, nil
}
func (UnimplementedPatentServiceServer) GetCitationNetwork(context.Context, *GetCitationNetworkRequest) (*GetCitationNetworkResponse, error) {
	return nil, nil
}
func (UnimplementedPatentServiceServer) mustEmbedUnimplementedPatentServiceServer() {}

// UnsafePatentServiceServer may be embedded to opt out of forward compatibility.
type UnsafePatentServiceServer interface {
	mustEmbedUnimplementedPatentServiceServer()
}

// RegisterPatentServiceServer registers the PatentServiceServer with the grpc.Server.
func RegisterPatentServiceServer(s grpc.ServiceRegistrar, srv PatentServiceServer) {
	s.RegisterService(&PatentService_ServiceDesc, srv)
}

// PatentService_ServiceDesc is the grpc.ServiceDesc for PatentService service.
var PatentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "patent.v1.PatentService",
	HandlerType: (*PatentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "GetPatent", Handler: nil},
		{MethodName: "SearchPatents", Handler: nil},
		{MethodName: "AnalyzeClaims", Handler: nil},
		{MethodName: "CheckFTO", Handler: nil},
		{MethodName: "GetPatentFamily", Handler: nil},
		{MethodName: "GetCitationNetwork", Handler: nil},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "patent/v1/patent.proto",
}

//Personal.AI order the ending
