// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a stub file for compilation compatibility.
// For production, generate from patent.proto using protoc.

package v1

// Patent represents a patent message.
type Patent struct {
	PatentNumber    string   `json:"patent_number,omitempty"`
	Title           string   `json:"title,omitempty"`
	Abstract        string   `json:"abstract,omitempty"`
	Applicants      []string `json:"applicants,omitempty"`
	Inventors       []string `json:"inventors,omitempty"`
	IpcClasses      []string `json:"ipc_classes,omitempty"`
	CpcClasses      []string `json:"cpc_classes,omitempty"`
	PatentOffice    string   `json:"patent_office,omitempty"`
	ApplicationDate int64    `json:"application_date,omitempty"`
	PublicationDate int64    `json:"publication_date,omitempty"`
	GrantDate       int64    `json:"grant_date,omitempty"`
	LegalStatus     string   `json:"legal_status,omitempty"`
	ClaimsCount     int32    `json:"claims_count,omitempty"`
	CitationsCount  int32    `json:"citations_count,omitempty"`
	FamilyId        string   `json:"family_id,omitempty"`
	PriorityNumber  string   `json:"priority_number,omitempty"`
	PriorityDate    int64    `json:"priority_date,omitempty"`
}

// GetPatentRequest is the request for GetPatent.
type GetPatentRequest struct {
	PatentNumber string `json:"patent_number,omitempty"`
}

// GetPatentResponse is the response for GetPatent.
type GetPatentResponse struct {
	Patent *Patent `json:"patent,omitempty"`
}

// SearchPatentsRequest is the request for SearchPatents.
type SearchPatentsRequest struct {
	Query               string   `json:"query,omitempty"`
	IpcClasses          []string `json:"ipc_classes,omitempty"`
	CpcClasses          []string `json:"cpc_classes,omitempty"`
	PatentOffices       []string `json:"patent_offices,omitempty"`
	ApplicationDateFrom int64    `json:"application_date_from,omitempty"`
	ApplicationDateTo   int64    `json:"application_date_to,omitempty"`
	PublicationDateFrom int64    `json:"publication_date_from,omitempty"`
	PublicationDateTo   int64    `json:"publication_date_to,omitempty"`
	PageSize            int32    `json:"page_size,omitempty"`
	PageToken           string   `json:"page_token,omitempty"`
	SortBy              string   `json:"sort_by,omitempty"`
	SortOrder           string   `json:"sort_order,omitempty"`
}

// SearchPatentsResponse is the response for SearchPatents.
type SearchPatentsResponse struct {
	Patents       []*Patent `json:"patents,omitempty"`
	NextPageToken string    `json:"next_page_token,omitempty"`
	TotalCount    int64     `json:"total_count,omitempty"`
}

// AnalyzeClaimsRequest is the request for AnalyzeClaims.
type AnalyzeClaimsRequest struct {
	PatentNumber string `json:"patent_number,omitempty"`
}

// Claim represents a patent claim.
type Claim struct {
	ClaimNumber       int32    `json:"claim_number,omitempty"`
	ClaimText         string   `json:"claim_text,omitempty"`
	ClaimType         string   `json:"claim_type,omitempty"`
	IsIndependent     bool     `json:"is_independent,omitempty"`
	DependsOn         []int32  `json:"depends_on,omitempty"`
	DependentClaims   []*Claim `json:"dependent_claims,omitempty"`
	TechnicalFeatures []string `json:"technical_features,omitempty"`
}

// ClaimTree represents a claim tree structure.
type ClaimTree struct {
	IndependentClaims []*Claim `json:"independent_claims,omitempty"`
	TotalClaims       int32    `json:"total_claims,omitempty"`
	MaxDepth          int32    `json:"max_depth,omitempty"`
}

// AnalyzeClaimsResponse is the response for AnalyzeClaims.
type AnalyzeClaimsResponse struct {
	PatentNumber       string     `json:"patent_number,omitempty"`
	ClaimTree          *ClaimTree `json:"claim_tree,omitempty"`
	IndependentCount   int32      `json:"independent_count,omitempty"`
	DependentCount     int32      `json:"dependent_count,omitempty"`
	TotalClaims        int32      `json:"total_claims,omitempty"`
	MaxDependencyDepth int32      `json:"max_dependency_depth,omitempty"`
}

// CheckFTORequest is the request for CheckFTO.
type CheckFTORequest struct {
	TargetSmiles   string `json:"target_smiles,omitempty"`
	Jurisdiction   string `json:"jurisdiction,omitempty"`
	IncludeExpired bool   `json:"include_expired,omitempty"`
}

// BlockingPatent represents a blocking patent.
type BlockingPatent struct {
	PatentNumber  string   `json:"patent_number,omitempty"`
	Title         string   `json:"title,omitempty"`
	RiskLevel     string   `json:"risk_level,omitempty"`
	Similarity    float64  `json:"similarity,omitempty"`
	ExpiryDate    int64    `json:"expiry_date,omitempty"`
	LegalStatus   string   `json:"legal_status,omitempty"`
	MatchedClaims []int32  `json:"matched_claims,omitempty"`
}

// CheckFTOResponse is the response for CheckFTO.
type CheckFTOResponse struct {
	CanOperate      bool              `json:"can_operate,omitempty"`
	RiskLevel       string            `json:"risk_level,omitempty"`
	Confidence      float64           `json:"confidence,omitempty"`
	BlockingPatents []*BlockingPatent `json:"blocking_patents,omitempty"`
	Recommendation  string            `json:"recommendation,omitempty"`
	CheckedAt       int64             `json:"checked_at,omitempty"`
}

// GetPatentFamilyRequest is the request for GetPatentFamily.
type GetPatentFamilyRequest struct {
	PatentNumber string `json:"patent_number,omitempty"`
}

// FamilyMember represents a patent family member.
type FamilyMember struct {
	PatentNumber     string `json:"patent_number,omitempty"`
	PatentOffice     string `json:"patent_office,omitempty"`
	ApplicationDate  int64  `json:"application_date,omitempty"`
	PublicationDate  int64  `json:"publication_date,omitempty"`
	LegalStatus      string `json:"legal_status,omitempty"`
	IsRepresentative bool   `json:"is_representative,omitempty"`
}

// GetPatentFamilyResponse is the response for GetPatentFamily.
type GetPatentFamilyResponse struct {
	FamilyId      string          `json:"family_id,omitempty"`
	FamilyMembers []*FamilyMember `json:"family_members,omitempty"`
	TotalMembers  int32           `json:"total_members,omitempty"`
}

// GetCitationNetworkRequest is the request for GetCitationNetwork.
type GetCitationNetworkRequest struct {
	PatentNumber   string `json:"patent_number,omitempty"`
	Depth          int32  `json:"depth,omitempty"`
	IncludeCiting  bool   `json:"include_citing,omitempty"`
	IncludeCited   bool   `json:"include_cited,omitempty"`
}

// CitationNode represents a node in the citation network.
type CitationNode struct {
	PatentNumber    string `json:"patent_number,omitempty"`
	Title           string `json:"title,omitempty"`
	PublicationDate int64  `json:"publication_date,omitempty"`
	CitationLevel   int32  `json:"citation_level,omitempty"`
	IsRoot          bool   `json:"is_root,omitempty"`
}

// CitationEdge represents an edge in the citation network.
type CitationEdge struct {
	FromPatent string `json:"from_patent,omitempty"`
	ToPatent   string `json:"to_patent,omitempty"`
	EdgeType   string `json:"edge_type,omitempty"`
}

// GetCitationNetworkResponse is the response for GetCitationNetwork.
type GetCitationNetworkResponse struct {
	Nodes       []*CitationNode `json:"nodes,omitempty"`
	Edges       []*CitationEdge `json:"edges,omitempty"`
	TotalNodes  int32           `json:"total_nodes,omitempty"`
	TotalEdges  int32           `json:"total_edges,omitempty"`
	IsTruncated bool            `json:"is_truncated,omitempty"`
}

//Personal.AI order the ending
